import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <nav className="bg-gray-700 flex gap-4 p-4 text-lg">
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/sheryians">Sheryians</Link>
        <Link href="/sheryians/classroom">Classroom</Link>
      </nav>

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
